# Generated by Django 5.2.1 on 2025-06-23 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_remove_contact_category_remove_contact_created_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rua',
            name='bairro',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
