# Generated by Django 5.2.1 on 2025-06-25 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0005_rua_description_aulacrianca_circuloestudo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupofamilias',
            name='familias',
            field=models.ManyToManyField(blank=True, related_name='grupos_familias', to='contact.familia'),
        ),
    ]
