# Generated by Django 5.2.1 on 2025-06-26 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0006_grupofamilias_familias'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grupofamilias',
            name='data_ultima_reflexao',
        ),
        migrations.AddField(
            model_name='grupofamilias',
            name='data_ultima_reuniao_reflexao',
            field=models.DateField(blank=True, null=True, verbose_name='Data da última reunião de reflexão'),
        ),
        migrations.AlterField(
            model_name='aulacrianca',
            name='rua',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aulas_crianca', to='contact.rua'),
        ),
        migrations.AlterField(
            model_name='grupofamilias',
            name='familias',
            field=models.ManyToManyField(blank=True, to='contact.familia'),
        ),
        migrations.AlterField(
            model_name='grupofamilias',
            name='participantes',
            field=models.ManyToManyField(blank=True, to='contact.contact'),
        ),
        migrations.AlterField(
            model_name='grupofamilias',
            name='ruas',
            field=models.ManyToManyField(blank=True, to='contact.rua'),
        ),
    ]
