# Generated by Django 5.2.1 on 2025-06-26 10:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0007_remove_grupofamilias_data_ultima_reflexao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupoprejovens',
            name='animador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grupos_pre_jovens_como_animador', to='contact.contact'),
        ),
    ]
