# Generated by Django 5.2.1 on 2025-06-26 11:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0008_grupoprejovens_animador'),
    ]

    operations = [
        migrations.AddField(
            model_name='circuloestudo',
            name='rua',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='circulos_estudo', to='contact.rua'),
        ),
    ]
