# Generated by Django 5.2.7 on 2025-10-28 19:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0009_circuloestudo_rua'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LivroRuhi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_livro', models.CharField(choices=[('Livro 1', 'Livro 1 - Reflexões sobre a Vida do Espírito'), ('Livro 2', 'Livro 2 - Surgindo para Servir'), ('Livro 3', 'Livro 3 - Caminhando numa Senda de Serviço'), ('Livro 4', 'Livro 4 - Os Gêmeos da Luz'), ('Livro 5', 'Livro 5 - Liberando Poderes'), ('Livro 6', 'Livro 6 - Ensinando Crianças - Grau 1'), ('Livro 7', 'Livro 7 - Caminhando com Deus'), ('Livro 8', "Livro 8 - O Convênio de Bahá'u'lláh"), ('Livro 9', 'Livro 9 - Ganhando uma Perspectiva Histórica'), ('Livro 10', 'Livro 10 - Construindo Comunidades Vibrantes'), ('Livro 11', 'Livro 11 - Materiais para Ações Devocinas'), ('Livro 12', 'Livro 12 - A Realidade da Natureza Humana'), ('Livro 13', 'Livro 13 - Promovendo o Bem-estar dos Jovens'), ('Livro 14', 'Livro 14 - Servindo como Tutor')], max_length=100)),
                ('data_inicio', models.DateField(blank=True, help_text='Data em que começou a estudar o livro', null=True)),
                ('data_termino', models.DateField(blank=True, help_text='Data em que terminou o livro', null=True)),
                ('status', models.CharField(choices=[('nao_iniciado', 'Não Iniciado'), ('em_andamento', 'Em Andamento'), ('concluido', 'Concluído'), ('pausado', 'Pausado')], default='nao_iniciado', max_length=20)),
                ('observacoes', models.TextField(blank=True, help_text='Observações sobre o estudo do livro')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='livros_ruhi', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Livro Ruhi',
                'verbose_name_plural': 'Livros Ruhi',
                'ordering': ['nome_livro'],
                'unique_together': {('usuario', 'nome_livro')},
            },
        ),
    ]
