# Generated by Django 5.2.7 on 2025-10-28 19:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0010_livroruhi'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(help_text='Número do livro (1, 2, 3, etc.)', unique=True)),
                ('titulo', models.CharField(help_text='Título completo do livro', max_length=200)),
                ('descricao', models.TextField(blank=True, help_text='Descrição do conteúdo do livro')),
                ('ativo', models.BooleanField(default=True, help_text='Se o livro está disponível para estudo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Livro do Instituto Ruhi',
                'verbose_name_plural': 'Livros do Instituto Ruhi',
                'ordering': ['numero'],
            },
        ),
        migrations.CreateModel(
            name='EstudoLivro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField(blank=True, help_text='Data em que começou a estudar o livro', null=True)),
                ('data_termino', models.DateField(blank=True, help_text='Data em que terminou o livro', null=True)),
                ('status', models.CharField(choices=[('nao_iniciado', 'Não Iniciado'), ('em_andamento', 'Em Andamento'), ('concluido', 'Concluído'), ('pausado', 'Pausado')], default='nao_iniciado', max_length=20)),
                ('observacoes', models.TextField(blank=True, help_text='Observações sobre o estudo do livro')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estudos', to='contact.contact')),
                ('owner', models.ForeignKey(help_text='Usuário que gerencia este estudo', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('livro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estudos', to='contact.livro')),
            ],
            options={
                'verbose_name': 'Estudo de Livro',
                'verbose_name_plural': 'Estudos de Livros',
                'ordering': ['livro__numero', 'contato__first_name'],
                'unique_together': {('contato', 'livro')},
            },
        ),
        migrations.DeleteModel(
            name='LivroRuhi',
        ),
    ]
