# Generated by Django 5.2.7 on 2025-10-28 20:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0011_livro_estudolivro_delete_livroruhi'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='data_inicio_estudo',
            field=models.DateField(blank=True, help_text='Data que começou a estudar o livro atual', null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='data_termino_estudo',
            field=models.DateField(blank=True, help_text='Data que terminou o livro atual', null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='livro_estudando',
            field=models.ForeignKey(blank=True, help_text='Livro que está estudando atualmente', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estudantes', to='contact.livro'),
        ),
        migrations.AddField(
            model_name='contact',
            name='observacoes_estudo',
            field=models.TextField(blank=True, help_text='Observações sobre o estudo atual'),
        ),
        migrations.AddField(
            model_name='contact',
            name='status_estudo',
            field=models.CharField(choices=[('nao_iniciado', 'Não Iniciado'), ('em_andamento', 'Em Andamento'), ('concluido', 'Concluído'), ('pausado', 'Pausado')], default='nao_iniciado', help_text='Status do estudo atual', max_length=20),
        ),
        migrations.DeleteModel(
            name='EstudoLivro',
        ),
    ]
