# Generated by Django 5.2.7 on 2025-10-28 20:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0012_contact_data_inicio_estudo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='circuloestudo',
            name='livro_ruhi',
            field=models.ForeignKey(blank=True, help_text='Livro do Instituto Ruhi que está sendo estudado', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='circulos_estudo', to='contact.livro'),
        ),
        migrations.AlterField(
            model_name='circuloestudo',
            name='livro',
            field=models.CharField(blank=True, help_text='Campo antigo - será removido em migração futura', max_length=100),
        ),
    ]
