# Generated by Django 5.2.7 on 2025-10-28 20:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0013_circuloestudo_livro_ruhi_alter_circuloestudo_livro'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoEstudo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('concluido', 'Concluído'), ('interrompido', 'Interrompido')], default='concluido', max_length=20)),
                ('data_inicio', models.DateField(blank=True, help_text='Data de início do estudo', null=True)),
                ('data_termino', models.DateField(blank=True, help_text='Data de conclusão ou interrupção', null=True)),
                ('observacoes', models.TextField(blank=True, help_text='Observações sobre o estudo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_estudos', to='contact.contact')),
                ('livro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_estudos', to='contact.livro')),
            ],
            options={
                'verbose_name': 'Histórico de Estudo',
                'verbose_name_plural': 'Histórico de Estudos',
                'ordering': ['-data_termino', '-created_at'],
                'unique_together': {('contato', 'livro')},
            },
        ),
    ]
