# Generated by Django 5.2.7 on 2025-10-28 20:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0014_historicoestudo'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstudoAtual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('em_andamento', 'Em Andamento'), ('pausado', 'Pausado')], default='em_andamento', max_length=20)),
                ('data_inicio', models.DateField(blank=True, help_text='Data de início do estudo', null=True)),
                ('observacoes', models.TextField(blank=True, help_text='Observações sobre o estudo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estudos_atuais', to='contact.contact')),
                ('livro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estudos_atuais', to='contact.livro')),
            ],
            options={
                'verbose_name': 'Estudo Atual',
                'verbose_name_plural': 'Estudos Atuais',
                'ordering': ['-created_at'],
                'unique_together': {('contato', 'livro')},
            },
        ),
    ]
