# Generated by Django 5.2.7 on 2025-10-28 21:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0015_estudoatual'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaLivro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text="Nome da categoria (ex: Instituto Ruhi, Aulas Bahá'ís para Crianças)", max_length=200)),
                ('descricao', models.TextField(blank=True, help_text='Descrição da categoria')),
                ('cor', models.CharField(default='#007bff', help_text='Cor da categoria em hexadecimal', max_length=7)),
                ('ordem', models.PositiveIntegerField(default=0, help_text='Ordem de exibição')),
                ('ativo', models.BooleanField(default=True, help_text='Se a categoria está ativa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Categoria de Livro',
                'verbose_name_plural': 'Categorias de Livros',
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.AlterModelOptions(
            name='livro',
            options={'ordering': ['categoria__ordem', 'categoria__nome', 'numero'], 'verbose_name': 'Livro', 'verbose_name_plural': 'Livros'},
        ),
        migrations.AlterField(
            model_name='livro',
            name='numero',
            field=models.PositiveIntegerField(help_text='Número do livro/série (1, 2, 3, etc.)'),
        ),
        migrations.AddField(
            model_name='livro',
            name='categoria',
            field=models.ForeignKey(blank=True, help_text='Categoria do livro', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='livros', to='contact.categorialivro'),
        ),
    ]
