# Generated by Django 5.2.7 on 2025-10-28 21:43

from django.db import migrations


def create_default_categories(apps, schema_editor):
    """Criar categorias padrão e associar livros existentes"""
    CategoriaLivro = apps.get_model('contact', 'CategoriaLivro')
    Livro = apps.get_model('contact', 'Livro')
    
    # Criar categorias padrão
    instituto_ruhi, created = CategoriaLivro.objects.get_or_create(
        nome='Instituto Ruhi',
        defaults={
            'descricao': 'Livros principais do Instituto Ruhi para jovens e adultos',
            'cor': '#007bff',
            'ordem': 1
        }
    )
    
    aulas_criancas, created = CategoriaLivro.objects.get_or_create(
        nome='Aulas Bahá\'ís para Crianças',
        defaults={
            'descricao': 'Materiais educacionais para aulas de crianças',
            'cor': '#28a745',
            'ordem': 2
        }
    )
    
    pre_jovens, created = CategoriaLivro.objects.get_or_create(
        nome='Programa de Pré-Jovens',
        defaults={
            'descricao': 'Livros e materiais para o programa de pré-jovens',
            'cor': '#ffc107',
            'ordem': 3
        }
    )
    
    # Associar todos os livros existentes ao Instituto Ruhi
    Livro.objects.filter(categoria__isnull=True).update(categoria=instituto_ruhi)


def reverse_default_categories(apps, schema_editor):
    """Reverter a criação das categorias padrão"""
    CategoriaLivro = apps.get_model('contact', 'CategoriaLivro')
    Livro = apps.get_model('contact', 'Livro')
    
    # Remover associação dos livros
    Livro.objects.all().update(categoria=None)
    
    # Remover categorias
    CategoriaLivro.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0016_categorialivro_alter_livro_options_and_more'),
    ]

    operations = [
        migrations.RunPython(create_default_categories, reverse_default_categories),
    ]
