# Generated by Django 5.2.7 on 2025-10-28 23:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0017_auto_20251028_1843'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoEstatisticas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_plano', models.CharField(default='Plano de 9 Anos', max_length=100)),
                ('data_inicio_contagem', models.DateField(help_text='Data de início da contagem de ciclos')),
                ('ciclo1_inicio', models.CharField(default='01-21', help_text='Formato: MM-DD', max_length=5)),
                ('ciclo1_fim', models.CharField(default='04-20', help_text='Formato: MM-DD', max_length=5)),
                ('ciclo2_inicio', models.CharField(default='04-21', help_text='Formato: MM-DD', max_length=5)),
                ('ciclo2_fim', models.CharField(default='07-20', help_text='Formato: MM-DD', max_length=5)),
                ('ciclo3_inicio', models.CharField(default='07-21', help_text='Formato: MM-DD', max_length=5)),
                ('ciclo3_fim', models.CharField(default='10-20', help_text='Formato: MM-DD', max_length=5)),
                ('ciclo4_inicio', models.CharField(default='10-21', help_text='Formato: MM-DD', max_length=5)),
                ('ciclo4_fim', models.CharField(default='01-20', help_text='Formato: MM-DD', max_length=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Configuração de Estatísticas',
                'verbose_name_plural': 'Configurações de Estatísticas',
            },
        ),
        migrations.CreateModel(
            name='EstatisticasEditaveis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_grupos_prejovens', models.IntegerField(default=0, help_text='Número total de grupos de pré-jovens')),
                ('participantes_prejovens', models.IntegerField(default=0)),
                ('participantes_prejovens_bahais', models.IntegerField(default=0)),
                ('total_aulas_criancas', models.IntegerField(default=0, help_text="Número total de aulas bahá'ís para crianças")),
                ('participantes_criancas', models.IntegerField(default=0)),
                ('participantes_criancas_bahais', models.IntegerField(default=0)),
                ('total_circulos_estudo', models.IntegerField(default=0, help_text='Número total de círculos de estudo')),
                ('participantes_circulos', models.IntegerField(default=0)),
                ('participantes_circulos_bahais', models.IntegerField(default=0)),
                ('total_jovens', models.IntegerField(default=0, help_text='Total de jovens (15-30 anos)')),
                ('total_criancas', models.IntegerField(default=0, help_text='Total de crianças (até 14 anos)')),
                ('total_adultos', models.IntegerField(default=0, help_text='Total de adultos (30+ anos)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Estatísticas Editáveis',
                'verbose_name_plural': 'Estatísticas Editáveis',
            },
        ),
    ]
