# Generated by Django 5.2.7 on 2025-10-29 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0018_configuracaoestatisticas_estatisticaseditaveis'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuracaoestatisticas',
            name='data_inicio_contagem',
        ),
        migrations.AddField(
            model_name='configuracaoestatisticas',
            name='ativo',
            field=models.BooleanField(default=True, help_text='Se o plano está ativo ou encerrado'),
        ),
        migrations.AddField(
            model_name='configuracaoestatisticas',
            name='data_inicio_plano',
            field=models.DateField(default='2022-01-01', help_text='Data de início do primeiro ciclo do plano'),
        ),
        migrations.AddField(
            model_name='configuracaoestatisticas',
            name='duracao_ciclo_meses',
            field=models.IntegerField(default=3, help_text='Duração de cada ciclo em meses'),
        ),
        migrations.AddField(
            model_name='configuracaoestatisticas',
            name='total_ciclos_plano',
            field=models.IntegerField(default=36, help_text='Total de ciclos no plano completo'),
        ),
    ]
