# Generated by Django 5.2.7 on 2025-10-29 00:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0020_auto_20251028_2104'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='estatisticaseditaveis',
            name='participantes_devocionais',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='estatisticaseditaveis',
            name='participantes_devocionais_bahais',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='estatisticaseditaveis',
            name='total_reunioes_devocionais',
            field=models.IntegerField(default=0, help_text='Número total de reuniões devocionais'),
        ),
        migrations.CreateModel(
            name='ReuniaoDevocional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, help_text='Nome ou identificação da reunião devocional', max_length=100)),
                ('descricao', models.TextField(blank=True, help_text='Descrição da reunião devocional')),
                ('local_detalhes', models.CharField(blank=True, help_text='Detalhes do local (casa, centro comunitário, etc.)', max_length=200)),
                ('numero_participantes', models.IntegerField(default=0, help_text='Número de participantes na reunião')),
                ('participantes_bahais', models.IntegerField(default=0, help_text="Quantos participantes são Bahá'ís")),
                ('dia_semana', models.CharField(blank=True, help_text='Dia da semana que acontece', max_length=20)),
                ('horario', models.TimeField(blank=True, help_text='Horário da reunião', null=True)),
                ('frequencia', models.CharField(choices=[('Semanal', 'Semanal'), ('Quinzenal', 'Quinzenal'), ('Mensal', 'Mensal'), ('Esporádica', 'Esporádica')], default='Semanal', max_length=50)),
                ('ativa', models.BooleanField(default=True, help_text='Se a reunião está ativa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('rua', models.ForeignKey(blank=True, help_text='Local onde acontece a reunião', null=True, on_delete=django.db.models.deletion.SET_NULL, to='contact.rua')),
            ],
            options={
                'verbose_name': 'Reunião Devocional',
                'verbose_name_plural': 'Reuniões Devocionais',
                'ordering': ['-ativa', 'dia_semana', 'horario'],
            },
        ),
    ]
