# Generated by Django 5.2.7 on 2025-10-29 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0021_estatisticaseditaveis_participantes_devocionais_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estatisticaseditaveis',
            name='animadores_prejovens',
            field=models.IntegerField(default=0, help_text='Número de animadores de pré-jovens'),
        ),
        migrations.AddField(
            model_name='estatisticaseditaveis',
            name='circulos_concluidos',
            field=models.IntegerField(default=0, help_text='Círculos concluídos no último ciclo'),
        ),
        migrations.AddField(
            model_name='estatisticaseditaveis',
            name='facilitadores_devocionais',
            field=models.IntegerField(default=0, help_text='Número de facilitadores de reuniões devocionais'),
        ),
        migrations.AddField(
            model_name='estatisticaseditaveis',
            name='livros_circulos',
            field=models.CharField(blank=True, help_text='Livros sendo estudados', max_length=200),
        ),
        migrations.AddField(
            model_name='estatisticaseditaveis',
            name='locais_prejovens',
            field=models.IntegerField(default=0, help_text='Número de locais onde grupos se reúnem'),
        ),
        migrations.AddField(
            model_name='estatisticaseditaveis',
            name='professores_criancas',
            field=models.IntegerField(default=0, help_text='Número de professores de aulas para crianças'),
        ),
        migrations.AddField(
            model_name='estatisticaseditaveis',
            name='series_criancas',
            field=models.CharField(blank=True, help_text='Séries sendo estudadas', max_length=200),
        ),
        migrations.AddField(
            model_name='estatisticaseditaveis',
            name='tutores_circulos',
            field=models.IntegerField(default=0, help_text='Número de tutores de círculos'),
        ),
    ]
