# Generated by Django 5.2.7 on 2025-10-29 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0022_estatisticaseditaveis_animadores_prejovens_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='is_bahai',
            field=models.BooleanField(default=False, help_text="Marque se a pessoa é Bahá'í"),
        ),
    ]
