# Generated by Django 5.2.7 on 2025-10-29 04:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0024_add_is_bahai_field'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoCiclo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_ciclo', models.IntegerField()),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('total_circulos_estudo', models.IntegerField(default=0)),
                ('total_grupos_prejovens', models.IntegerField(default=0)),
                ('total_aulas_criancas', models.IntegerField(default=0)),
                ('total_reunioes_devocionais', models.IntegerField(default=0)),
                ('total_grupos_familias', models.IntegerField(default=0)),
                ('participantes_circulos', models.IntegerField(default=0)),
                ('participantes_prejovens', models.IntegerField(default=0)),
                ('participantes_criancas', models.IntegerField(default=0)),
                ('participantes_devocionais', models.IntegerField(default=0)),
                ('participantes_grupos_familias', models.IntegerField(default=0)),
                ('total_livros', models.IntegerField(default=0)),
                ('livros_iniciados', models.IntegerField(default=0)),
                ('livros_concluidos', models.IntegerField(default=0)),
                ('crescimento_atividades', models.FloatField(default=0.0)),
                ('crescimento_participantes', models.FloatField(default=0.0)),
                ('crescimento_livros', models.FloatField(default=0.0)),
                ('data_registro', models.DateTimeField(auto_now_add=True)),
                ('configuracao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historicos', to='contact.configuracaoestatisticas')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Histórico de Ciclo',
                'verbose_name_plural': 'Históricos de Ciclos',
                'ordering': ['-numero_ciclo'],
                'unique_together': {('configuracao', 'numero_ciclo')},
            },
        ),
    ]
