# Generated by Django 5.2.7 on 2025-10-29 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0025_historicociclo'),
    ]

    operations = [
        migrations.AddField(
            model_name='estatisticaseditaveis',
            name='total_prejovens',
            field=models.IntegerField(default=0, help_text='Total de pré-jovens (15-17 anos)'),
        ),
        migrations.AlterField(
            model_name='estatisticaseditaveis',
            name='total_jovens',
            field=models.IntegerField(default=0, help_text='Total de jovens (18-30 anos)'),
        ),
    ]
