# Generated by Django 5.2.7 on 2025-10-29 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0026_estatisticaseditaveis_total_prejovens_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicociclo',
            name='livros_abc_concluidos',
            field=models.IntegerField(default=0, help_text='Livros de ABC concluídos no ciclo'),
        ),
        migrations.AddField(
            model_name='historicociclo',
            name='livros_abc_iniciados',
            field=models.IntegerField(default=0, help_text='Livros de ABC iniciados no ciclo'),
        ),
        migrations.AddField(
            model_name='historicociclo',
            name='livros_outros_concluidos',
            field=models.IntegerField(default=0, help_text='Outros livros concluídos no ciclo'),
        ),
        migrations.AddField(
            model_name='historicociclo',
            name='livros_outros_iniciados',
            field=models.IntegerField(default=0, help_text='Outros livros iniciados no ciclo'),
        ),
        migrations.AddField(
            model_name='historicociclo',
            name='livros_prejovens_concluidos',
            field=models.IntegerField(default=0, help_text='Livros de Pré-jovens concluídos no ciclo'),
        ),
        migrations.AddField(
            model_name='historicociclo',
            name='livros_prejovens_iniciados',
            field=models.IntegerField(default=0, help_text='Livros de Pré-jovens iniciados no ciclo'),
        ),
        migrations.AddField(
            model_name='historicociclo',
            name='livros_sequencia_concluidos',
            field=models.IntegerField(default=0, help_text='Livros da Sequência concluídos no ciclo'),
        ),
        migrations.AddField(
            model_name='historicociclo',
            name='livros_sequencia_iniciados',
            field=models.IntegerField(default=0, help_text='Livros da Sequência iniciados no ciclo'),
        ),
        migrations.AlterField(
            model_name='estatisticaseditaveis',
            name='total_criancas',
            field=models.IntegerField(default=0, help_text='Total de crianças (até 11 anos)'),
        ),
        migrations.AlterField(
            model_name='estatisticaseditaveis',
            name='total_jovens',
            field=models.IntegerField(default=0, help_text='Total de jovens (15-30 anos)'),
        ),
        migrations.AlterField(
            model_name='estatisticaseditaveis',
            name='total_prejovens',
            field=models.IntegerField(default=0, help_text='Total de pré-jovens (12-14 anos)'),
        ),
    ]
