# Generated by Django 5.2.7 on 2025-10-29 05:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0027_add_book_categories_to_historico'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalheLivroHistorico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('Sequência', 'Sequência (Ruhi)'), ('ABC', 'ABC (Aulas de Crianças)'), ('Pré-jovens', 'Pré-jovens'), ('Outros', 'Outros')], max_length=50)),
                ('nome_livro', models.CharField(help_text='Ex: Livro 1, Série 2, etc.', max_length=100)),
                ('quantidade_iniciados', models.IntegerField(default=0, help_text='Quantas pessoas iniciaram este livro')),
                ('quantidade_concluidos', models.IntegerField(default=0, help_text='Quantas pessoas concluíram este livro')),
                ('observacoes', models.TextField(blank=True, help_text='Observações específicas sobre este livro')),
                ('historico_ciclo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalhes_livros', to='contact.historicociclo')),
            ],
            options={
                'verbose_name': 'Detalhe de Livro no Histórico',
                'verbose_name_plural': 'Detalhes de Livros no Histórico',
                'ordering': ['categoria', 'nome_livro'],
                'unique_together': {('historico_ciclo', 'categoria', 'nome_livro')},
            },
        ),
    ]
