# Generated by Django 5.2.7 on 2025-10-29 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0029_alter_detalhelivrohistorico_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalhelivrohistorico',
            name='categoria',
            field=models.CharField(choices=[('sequencia', 'Sequência (Ruhi)'), ('abc', 'ABC (Aulas de Crianças)'), ('prejovens', 'Pré-jovens'), ('outros', 'Outros')], max_length=50),
        ),
    ]
