# Generated by Django 5.2.7 on 2025-10-29 17:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0030_alter_detalhelivrohistorico_categoria'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='aulacrianca',
            name='data_criacao_definida',
            field=models.DateField(blank=True, help_text='Data de criação para histórico', null=True),
        ),
        migrations.AddField(
            model_name='aulacrianca',
            name='numero_ciclo_criacao',
            field=models.IntegerField(blank=True, help_text='Número do ciclo de criação', null=True),
        ),
        migrations.AddField(
            model_name='aulacrianca',
            name='plano_ciclo',
            field=models.ForeignKey(blank=True, help_text='Plano de ciclos', null=True, on_delete=django.db.models.deletion.SET_NULL, to='contact.configuracaoestatisticas'),
        ),
        migrations.AddField(
            model_name='circuloestudo',
            name='data_criacao_definida',
            field=models.DateField(blank=True, help_text='Data específica de criação', null=True),
        ),
        migrations.AddField(
            model_name='circuloestudo',
            name='numero_ciclo_criacao',
            field=models.IntegerField(blank=True, help_text='Ciclo em que foi criado', null=True),
        ),
        migrations.AddField(
            model_name='circuloestudo',
            name='plano_ciclo',
            field=models.ForeignKey(blank=True, help_text='Plano de ciclos ao qual pertence', null=True, on_delete=django.db.models.deletion.SET_NULL, to='contact.configuracaoestatisticas'),
        ),
        migrations.AddField(
            model_name='configuracaoestatisticas',
            name='descricao',
            field=models.TextField(blank=True, help_text='Descrição opcional do plano'),
        ),
        migrations.AddField(
            model_name='configuracaoestatisticas',
            name='principal',
            field=models.BooleanField(default=True, help_text='Se é o plano principal (usado no dashboard)'),
        ),
        migrations.AddField(
            model_name='estudoatual',
            name='data_criacao_definida',
            field=models.DateField(blank=True, help_text='Data específica de criação', null=True),
        ),
        migrations.AddField(
            model_name='estudoatual',
            name='numero_ciclo_criacao',
            field=models.IntegerField(blank=True, help_text='Ciclo em que foi criado', null=True),
        ),
        migrations.AddField(
            model_name='estudoatual',
            name='plano_ciclo',
            field=models.ForeignKey(blank=True, help_text='Plano de ciclos ao qual pertence', null=True, on_delete=django.db.models.deletion.SET_NULL, to='contact.configuracaoestatisticas'),
        ),
        migrations.AddField(
            model_name='grupoprejovens',
            name='data_criacao_definida',
            field=models.DateField(blank=True, help_text='Data específica de criação (para dados históricos)', null=True),
        ),
        migrations.AddField(
            model_name='grupoprejovens',
            name='numero_ciclo_criacao',
            field=models.IntegerField(blank=True, help_text='Número do ciclo em que foi criado', null=True),
        ),
        migrations.AddField(
            model_name='grupoprejovens',
            name='plano_ciclo',
            field=models.ForeignKey(blank=True, help_text='Plano de ciclos em que foi criado', null=True, on_delete=django.db.models.deletion.SET_NULL, to='contact.configuracaoestatisticas'),
        ),
        migrations.AddField(
            model_name='historicoestudo',
            name='data_criacao_definida',
            field=models.DateField(blank=True, help_text='Data específica de criação', null=True),
        ),
        migrations.AddField(
            model_name='historicoestudo',
            name='numero_ciclo_criacao',
            field=models.IntegerField(blank=True, help_text='Ciclo em que foi criado', null=True),
        ),
        migrations.AddField(
            model_name='historicoestudo',
            name='plano_ciclo',
            field=models.ForeignKey(blank=True, help_text='Plano de ciclos ao qual pertence', null=True, on_delete=django.db.models.deletion.SET_NULL, to='contact.configuracaoestatisticas'),
        ),
        migrations.AlterField(
            model_name='configuracaoestatisticas',
            name='ativo',
            field=models.BooleanField(default=True, help_text='Se o plano está ativo'),
        ),
        migrations.AlterUniqueTogether(
            name='configuracaoestatisticas',
            unique_together={('owner', 'titulo_plano')},
        ),
    ]
