# Generated by Django 5.2.7 on 2025-10-29 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0031_aulacrianca_data_criacao_definida_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicociclo',
            name='participantes_circulos_bahais',
            field=models.IntegerField(default=0, help_text="Bahá'ís nos círculos de estudo"),
        ),
        migrations.AddField(
            model_name='historicociclo',
            name='participantes_criancas_bahais',
            field=models.IntegerField(default=0, help_text="Bahá'ís nas aulas de crianças"),
        ),
        migrations.AddField(
            model_name='historicociclo',
            name='participantes_devocionais_bahais',
            field=models.IntegerField(default=0, help_text="Bahá'ís nas reuniões devocionais"),
        ),
        migrations.AddField(
            model_name='historicociclo',
            name='participantes_grupos_familias_bahais',
            field=models.IntegerField(default=0, help_text="Bahá'ís nos grupos de famílias"),
        ),
        migrations.AddField(
            model_name='historicociclo',
            name='participantes_prejovens_bahais',
            field=models.IntegerField(default=0, help_text="Bahá'ís nos grupos de pré-jovens"),
        ),
    ]
