# Generated by Django 5.2.7 on 2025-10-29 18:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0032_historicociclo_participantes_circulos_bahais_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstatisticasEditaveisHistorico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_grupos_prejovens', models.IntegerField(default=0)),
                ('participantes_prejovens', models.IntegerField(default=0)),
                ('participantes_prejovens_bahais', models.IntegerField(default=0)),
                ('total_aulas_criancas', models.IntegerField(default=0)),
                ('participantes_criancas', models.IntegerField(default=0)),
                ('participantes_criancas_bahais', models.IntegerField(default=0)),
                ('total_circulos_estudo', models.IntegerField(default=0)),
                ('participantes_circulos', models.IntegerField(default=0)),
                ('participantes_circulos_bahais', models.IntegerField(default=0)),
                ('total_reunioes_devocionais', models.IntegerField(default=0)),
                ('participantes_devocionais', models.IntegerField(default=0)),
                ('participantes_devocionais_bahais', models.IntegerField(default=0)),
                ('animadores_prejovens', models.IntegerField(default=0)),
                ('locais_prejovens', models.IntegerField(default=0)),
                ('professores_criancas', models.IntegerField(default=0)),
                ('series_criancas', models.CharField(blank=True, max_length=200)),
                ('tutores_circulos', models.IntegerField(default=0)),
                ('livros_circulos', models.CharField(blank=True, max_length=200)),
                ('circulos_concluidos', models.IntegerField(default=0)),
                ('facilitadores_devocionais', models.IntegerField(default=0)),
                ('total_criancas', models.IntegerField(default=0)),
                ('total_prejovens', models.IntegerField(default=0)),
                ('total_jovens', models.IntegerField(default=0)),
                ('total_adultos', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('historico_ciclo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='estatisticas_editaveis', to='contact.historicociclo')),
            ],
            options={
                'verbose_name': 'Estatísticas Editáveis Históricas',
                'verbose_name_plural': 'Estatísticas Editáveis Históricas',
            },
        ),
    ]
