# Generated by Django 5.2.7 on 2025-10-29 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0033_estatisticaseditaveishistorico'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicociclo',
            name='sistema_aulas_criancas',
            field=models.IntegerField(default=0, help_text='Aulas de crianças contadas pelo sistema'),
        ),
        migrations.AddField(
            model_name='historicociclo',
            name='sistema_circulos_estudo',
            field=models.IntegerField(default=0, help_text='Círculos de estudo contados pelo sistema'),
        ),
        migrations.AddField(
            model_name='historicociclo',
            name='sistema_grupos_familias',
            field=models.IntegerField(default=0, help_text='Grupos de famílias contados pelo sistema'),
        ),
        migrations.AddField(
            model_name='historicociclo',
            name='sistema_grupos_prejovens',
            field=models.IntegerField(default=0, help_text='Grupos de pré-jovens contados pelo sistema'),
        ),
        migrations.AddField(
            model_name='historicociclo',
            name='sistema_participantes_circulos',
            field=models.IntegerField(default=0, help_text='Participantes em círculos contados pelo sistema'),
        ),
        migrations.AddField(
            model_name='historicociclo',
            name='sistema_participantes_circulos_bahais',
            field=models.IntegerField(default=0, help_text="Bahá'ís em círculos contados pelo sistema"),
        ),
        migrations.AddField(
            model_name='historicociclo',
            name='sistema_participantes_criancas',
            field=models.IntegerField(default=0, help_text='Participantes em aulas de crianças contados pelo sistema'),
        ),
        migrations.AddField(
            model_name='historicociclo',
            name='sistema_participantes_criancas_bahais',
            field=models.IntegerField(default=0, help_text="Bahá'ís em aulas de crianças contados pelo sistema"),
        ),
        migrations.AddField(
            model_name='historicociclo',
            name='sistema_participantes_devocionais',
            field=models.IntegerField(default=0, help_text='Participantes em reuniões devocionais contados pelo sistema'),
        ),
        migrations.AddField(
            model_name='historicociclo',
            name='sistema_participantes_devocionais_bahais',
            field=models.IntegerField(default=0, help_text="Bahá'ís em reuniões devocionais contados pelo sistema"),
        ),
        migrations.AddField(
            model_name='historicociclo',
            name='sistema_participantes_familias',
            field=models.IntegerField(default=0, help_text='Participantes em grupos de famílias contados pelo sistema'),
        ),
        migrations.AddField(
            model_name='historicociclo',
            name='sistema_participantes_familias_bahais',
            field=models.IntegerField(default=0, help_text="Bahá'ís em grupos de famílias contados pelo sistema"),
        ),
        migrations.AddField(
            model_name='historicociclo',
            name='sistema_participantes_prejovens',
            field=models.IntegerField(default=0, help_text='Participantes em grupos de pré-jovens contados pelo sistema'),
        ),
        migrations.AddField(
            model_name='historicociclo',
            name='sistema_participantes_prejovens_bahais',
            field=models.IntegerField(default=0, help_text="Bahá'ís em grupos de pré-jovens contados pelo sistema"),
        ),
        migrations.AddField(
            model_name='historicociclo',
            name='sistema_reunioes_devocionais',
            field=models.IntegerField(default=0, help_text='Reuniões devocionais contadas pelo sistema'),
        ),
        migrations.AddField(
            model_name='historicociclo',
            name='sistema_total_adultos',
            field=models.IntegerField(default=0, help_text='Total de adultos calculado pelo sistema'),
        ),
        migrations.AddField(
            model_name='historicociclo',
            name='sistema_total_criancas',
            field=models.IntegerField(default=0, help_text='Total de crianças calculado pelo sistema'),
        ),
        migrations.AddField(
            model_name='historicociclo',
            name='sistema_total_jovens',
            field=models.IntegerField(default=0, help_text='Total de jovens calculado pelo sistema'),
        ),
        migrations.AddField(
            model_name='historicociclo',
            name='sistema_total_prejovens',
            field=models.IntegerField(default=0, help_text='Total de pré-jovens calculado pelo sistema'),
        ),
    ]
