# Generated by Django 5.2.7 on 2025-10-29 20:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0034_add_sistema_fields_to_historico'),
    ]

    operations = [
        migrations.AddField(
            model_name='reuniaodevocional',
            name='numero_ciclo_criacao',
            field=models.IntegerField(blank=True, help_text='Número do ciclo em que foi criada', null=True),
        ),
        migrations.AddField(
            model_name='reuniaodevocional',
            name='plano_ciclo',
            field=models.ForeignKey(blank=True, help_text='Plano de ciclos ao qual esta reunião está associada', null=True, on_delete=django.db.models.deletion.SET_NULL, to='contact.configuracaoestatisticas'),
        ),
    ]
