# Generated by Django 5.2.7 on 2025-10-29 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0035_add_cycle_fields_to_reuniao_devocional'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicociclo',
            name='novas_aulas_criancas',
            field=models.IntegerField(default=0, help_text='Aulas de crianças criadas especificamente neste ciclo'),
        ),
        migrations.AddField(
            model_name='historicociclo',
            name='novas_circulos_estudo',
            field=models.IntegerField(default=0, help_text='Círculos de estudo criados especificamente neste ciclo'),
        ),
        migrations.AddField(
            model_name='historicociclo',
            name='novas_grupos_prejovens',
            field=models.IntegerField(default=0, help_text='Grupos de pré-jovens criados especificamente neste ciclo'),
        ),
        migrations.AddField(
            model_name='historicociclo',
            name='novas_reunioes_devocionais',
            field=models.IntegerField(default=0, help_text='Reuniões devocionais criadas especificamente neste ciclo'),
        ),
        migrations.AddField(
            model_name='historicociclo',
            name='novos_livros_abc',
            field=models.IntegerField(default=0, help_text='Livros de ABC iniciados especificamente neste ciclo'),
        ),
        migrations.AddField(
            model_name='historicociclo',
            name='novos_livros_concluidos',
            field=models.IntegerField(default=0, help_text='Livros concluídos especificamente neste ciclo'),
        ),
        migrations.AddField(
            model_name='historicociclo',
            name='novos_livros_iniciados',
            field=models.IntegerField(default=0, help_text='Livros iniciados especificamente neste ciclo'),
        ),
        migrations.AddField(
            model_name='historicociclo',
            name='novos_livros_outros',
            field=models.IntegerField(default=0, help_text='Outros livros iniciados especificamente neste ciclo'),
        ),
        migrations.AddField(
            model_name='historicociclo',
            name='novos_livros_prejovens',
            field=models.IntegerField(default=0, help_text='Livros de Pré-jovens iniciados especificamente neste ciclo'),
        ),
        migrations.AddField(
            model_name='historicociclo',
            name='novos_livros_sequencia',
            field=models.IntegerField(default=0, help_text='Livros da Sequência iniciados especificamente neste ciclo'),
        ),
    ]
