# Generated by Django 5.2.7 on 2025-10-29 21:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0036_add_atividades_novas_historico'),
    ]

    operations = [
        migrations.AddField(
            model_name='familia',
            name='numero_ciclo_criacao',
            field=models.IntegerField(blank=True, help_text='Número do ciclo em que a RD foi criada', null=True),
        ),
        migrations.AddField(
            model_name='familia',
            name='plano_ciclo',
            field=models.ForeignKey(blank=True, help_text='Plano de ciclos da RD', null=True, on_delete=django.db.models.deletion.SET_NULL, to='contact.configuracaoestatisticas'),
        ),
    ]
