# Generated by Django 5.2.7 on 2025-10-29 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0037_add_cycle_fields_to_familia'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicociclo',
            name='novas_familias_rds',
            field=models.IntegerField(default=0, help_text='Famílias com RDs criadas especificamente neste ciclo'),
        ),
    ]
